### ISSUE TITLE
Error Spam: ghosting.lua attempt to index local 'owner' (a nil value)

### ISSUE THREAD

**Issue by sergun26** [LuaTenshi/APAnti#10]
[ERROR] addons/apanti/lua/modules/apa/ghosting.lua:107: attempt to index local 'owner' (a nil value)
  1. AntiSpam - addons/apanti/lua/modules/apa/ghosting.lua:107
   2. fn - addons/apanti/lua/modules/apa/ghosting.lua:307
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

CFG:
apa_AntiPK 1
apa_BlockVehicleDamage  1
apa_BlockPropDamage 1
apa_BlockWorldDamage 1
apa_BlockPropDamage 1
apa_GhostPickup 1
apa_UnGhostPassive 0 -- Also this is make my server laggy when i set to 1
apa_GhostsNoCollide 0
apa_StopMassUnfreeze 1
apa_StopRUnfreeze 1
apa_NoThrow 1
apa_FreezeOnHit 0
apa_FreezeOnUnghost 0
apa_GhostFreeze 0
apa_GhostSpawn 1
apa_OnlyPlayers 0

**Comment by LuaTenshi** [comment]
Is this with the current version of APAnti (Github)? Also I am aware of UnGhostPassive lag, just haven't found a good way to fix it yet. Because I rolled back a bad update recently.

Also do you have FPP on your server?

**Comment by LuaTenshi** [comment]
Should be fixed now.

**Comment by sergun26** [comment]
I was using latest version (Github Beta)
Currently i installed the version you gave, this problem is fixed but another error accoured.

```
Lua Error: 
[ERROR] addons/apanti/lua/modules/apa/method0.lua:35: bad argument #1 to '(for generator)' (table expected, got nil)
  1. (for generator) - [C]:-1
   2. Think - addons/apanti/lua/modules/apa/method0.lua:35
    3. unknown - addons/apanti/lua/modules/apa/method0.lua:147

```

Yeah, i have FPP on my server.

Also sorry; I can't speak English as well.
