### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by Losos50** [LuaTenshi/APAnti#18]
|APAnti - Plugins Called|
> Ghosting
 
[ERROR] addons/apanti-master/lua/modules/apa/ghosting.lua:256: ')' expected near 'then'
  1. unknown - addons/apanti-master/lua/modules/apa/ghosting.lua:0
 
> Metahook
> Method0
|APAnti - Plugins Loaded|

**Comment by Geoffry-Skionfinschii** [comment]
Can be fixed by going to line 256 of addon\lua\modules\apa\ghosting.lua
`if(tostring(property) == "collision" then`
Change to:
`if(tostring(property) == "collision")`

**Comment by Losos50** [comment]
Yeah I fixed it like 25 days ago..
