### ISSUE TITLE
UnGhostPassive 1 causes the server to freeze

### ISSUE THREAD

**Issue by JokerR3310** [LuaTenshi/APAnti#2]
So, if **UnGhostPassive** set to **1** whole server just got frozen right after **any** prop get unfrozen by tapping R or right mouse button, no matter how.

This continue happening even in singleplayer and one way to close the game is end hl2.exe in task manager.

There absolutely no errors or dump files, server just got frozen but not-crashed.

**Comment by LuaTenshi** [comment]
Odd had no other reports of this issue, nor could I replicate this on my
server. What other add-ons are you running? Anything in console? Server
settings?

**Comment by LuaTenshi** [comment]
I will make freezing procedural to prevent any possible lag, I will also
make sure that it only effects props.

**Comment by JokerR3310** [comment]
I know about fact that other add-ons can cause conflicts, so that why i also try this on clean gmod and got the same result.
Are you sure that you set UnGhostPassive to 1 ? Because convar apa_unghostpassive seems 
not working at all, can you try set it to 1 direcly from autorun/server/apa_init.lua ?

Sorry for video quality.
https://www.youtube.com/watch?v=RHApDxTljX4

**Comment by LuaTenshi** [comment]
I'll check it out. Might have broken it in an update as I've been focusing
more on the default settings that most servers use. Expect a large change
to that feature in the near future.

**Comment by LuaTenshi** [comment]
Sorry for the long wait, I will be on top of this soon. ^^;

**Comment by JokerR3310** [comment]
Nice, thank you

**Comment by LuaTenshi** [comment]
Sorry for the long wait... I don't really have time to get gmod and test everything but I made a fix and you can get it [here](https://github.com/LuaTenshi/APAnti-TestBuild)

Please tell me if the following works. If it does not I will add debug stuff to that build and we can solve the problem together.

**Comment by LuaTenshi** [comment]
Update: Got it working try out the test build here and tell me if it fixes your problem. https://github.com/LuaTenshi/APAnti-TestBuild

**Comment by JokerR3310** [comment]
Yes, i can confirm that issue was fixed, but there is another problem.
If we walk into 'Ghosted' prop, notifications spam begin to appear.

Here the video:
https://www.youtube.com/watch?v=CeHLXTHL-K4

**Comment by LuaTenshi** [comment]
I am actually aware of that and that's why there are so many notices that
it's a test build. The bug will be fixed in the release.

**Comment by kulcris** [comment]
spawn any of the workspace props with UnGhostPassive 1 and the server will freeze

**Comment by LuaTenshi** [comment]
Hey if any one else is having this issue please be sure to check out the https://github.com/LuaTenshi/APAnti/tree/TEST and tell me if it works. I will be updating it periodically, then just push everything in one big update once it's ready to shine.

**Comment by LuaTenshi** [comment]
Fixed in https://github.com/LuaTenshi/APAnti/tree/TEST
