### ISSUE TITLE
FPP and APAnti Colliding 

### ISSUE THREAD

**Issue by auskfc** [LuaTenshi/APAnti#3]
I can still prop push if I quickly spawn in 2 props at once and use the second to push myself and others.

**Comment by LuaTenshi** [comment]
This is actually a conflict with FPP. Disable the anti prop spam ghosting
in FPP by setting the number to ghost props at higher then the number to
remove them. I will keep trying to work around this without having to have
people edit their FPP settings.

**Comment by LuaTenshi** [comment]
Should be fixed along with some other experimental fixes in the [test build](https://github.com/LuaTenshi/APAnti-TestBuild). 

Will commit to main after adding some promised/planned features.
