### ISSUE TITLE
bug with right admin

### ISSUE THREAD

**Issue by fantomeus** [LuaTenshi/APAnti#4]
i'm superadmin on a server and now with your APAnti admin can take me with physic gun :/

**Comment by LuaTenshi** [comment]
What admin mod are you using? This doesn't happen for me with ULX.

**Comment by fantomeus** [comment]
i use ulx, but when the server was not with your APAnti no bug with physics gun and now bug ... :/

**Comment by LuaTenshi** [comment]
Sorry for the long response delay but I couldn't really figure out what you were trying to say. If you are using a Prop Protection (like you should) this shouldn't happen.
