### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by dan2735** [LuaTenshi/APAnti#5]
When you physgun/ghost a prop that has an alpha color value it goes back to 255 when you unphysgun/unghost.

**Comment by LuaTenshi** [comment]
Hmm that's odd as it's supposed to save the alpha. I know Gmod has been weird with setting alpha in its code for the longest time. Hopefully I will be able to resolve this.

**Comment by dan2735** [comment]
Any ETA for a fix?

**Comment by LuaTenshi** [comment]
Sorry for the long delay on the response. But I have checked multiple times and it seems to be working fine for me and on other servers that I have visited.
