### ISSUE TITLE
You can't ride cars.

### ISSUE THREAD

**Issue by NonUhnonymous** [LuaTenshi/APAnti#6]
When I spawn in a car I can't ride in it, but if I set 	NoCollideVehicles 		= {0, "Setting this to 1 will make vehicles not collide with players."}, then I can get into cars again.  This means people can prop kill with the car which is what I don't want, but people can't even get into cars if I have this setting on. The cars are TDM and Sigs Bus

**Comment by LuaTenshi** [comment]
Looks like a TDM Cars issue. Other cars work fine with their collisions off. (By other I mean the default ones.)

**Comment by NonUhnonymous** [comment]
Alright, thanks for the response. I'll look for another addon that blocks car dmg.
