### ISSUE TITLE
CPPI not found despite ULX/ULIB installed on server.

### ISSUE THREAD

**Issue by RalphORama** [LuaTenshi/APAnti#7]
I'm messing around with setting up a Garry's Mod server, and I've run into an error with APAnti that I'm not sure how to fix. When I start the server, I get the following in console:

```
---------------------------------------------------------------
| [APA] ERROR: CPPI not found, Prop Protection not installed? |
---------------------------------------------------------------
[APA] CPPI not found, APAnti will be heavily limited.

File exists in two addons - possible conflicts! lua/ulib/shared/hook.lua (ULib and APAnti)

[ERROR] CPPI not found, APAnti will be heavily limited.
  1. error - [C]:-1
   2. unknown - lua/sv_apanti.lua:93
    3. include - [C]:-1
     4. fn - lua/autorun/server/apa_init.lua:98
      5. unknown - lua/ulib/shared/hook.lua:110
```

I'm not sure why this error occurs, as I've got ULX and ULIB installed. 

I'm using [this Workshop collection](http://steamcommunity.com/sharedfiles/filedetails/?id=129571525). I don't have anything else installed on my server.

You can find the full console output [here](https://glot.io/snippets/egvxyribwa)

**Comment by RalphORama** [comment]
Derp - I added `+gamemode darkrp` to my server start script, and everything started working.

**Comment by LuaTenshi** [comment]
CPPI is not part of ULX or ULIB. You need any CPPI based prop protection installed. ([FPP](https://github.com/FPtje/Falcos-Prop-protection), [PatchProtect](https://github.com/Patcher56/PatchProtect), [UPS](https://github.com/TeamUlysses/ups), etc.)
